apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: flask.rules
      rules:
        - alert: PodRestarting
          expr: sum by (pod, namespace, container) (increase(kube_pod_container_status_restarts_total{namespace="default", container="flask"}[5m])) > 0
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "Flask pod {{ $labels.pod }} restarted due to probe failure"

        - alert: PodNotReady
          expr: kube_pod_status_ready{namespace="default", condition="true"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} has been not ready for over 1 minute"
