apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    app: flask
spec:
  containers:
    - name: flask
      image: michaelzwang13/cloud-hw2:latest
      ports:
        - containerPort: 5001
      env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_ENV
          value: "production"
