alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname", "pod"]
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h
      receiver: slack
    receivers:
      - name: "null"
      - name: slack
        slack_configs:
          - api_url_secret:
              name: slack-webhook
              key: url
            channel: "#alerts"
            title: "{{ .GroupLabels.alertname }}"
            text: >-
              {{ range .Alerts }}
                *Pod:* {{ .Labels.pod | default "unknown" }}
                *Namespace:* {{ .Labels.namespace | default "unknown" }}
                *Container:* {{ .Labels.container | default "unknown" }}
                *Message:* {{ .Annotations.summary }}
              {{ end }}
            send_resolved: true

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: flask
        static_configs:
          - targets: ["flask.default.svc.cluster.local:5001"]
